stages:
  - lint
  - test

.ruby:
  image: "ruby:3.4"
  before_script: &ruby_before_script
    - ruby --version
    - bundle --version
    - gem --version
    - bundle install

rubocop:
  extends:
    - .ruby
  stage: lint
  script:
    - bin/rubocop

rspec:
  extends:
    - .ruby
  stage: test
  script:
    - bin/rspec
  coverage: "/Line Coverage: (\\d+\\.\\d+)%.*/"
