plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Layout/LineLength:
  Max: 80

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Style/StringLiterals:
  EnforcedStyle: double_quotes
