# frozen_string_literal: true

require "json"
require "nokogiri"
require_relative "jd/file_reader"
require_relative "jd/jsonl_reader"
require_relative "jd/file_writer"
require_relative "jd/jsonl_writer"
require_relative "jd/directory_writer"
require_relative "jd/xml_helpers"
require_relative "jd/xml_reader"
require_relative "jd/chiseids/reader"
require_relative "jd/jmdict/reader"
require_relative "jd/jmdictpri/priority_filter"
require_relative "jd/jmdictpri/reader"
require_relative "jd/jmnedict/reader"
require_relative "jd/jmnedictpri/reader"
require_relative "jd/kanjidep/dependency_resolver"
require_relative "jd/kanjidep/reader"
require_relative "jd/kanjidic/reader"
require_relative "jd/kanjidicdep/reader"
